quote/Quotes/urls.py
from django.urls import path
from . import views

app_name='Quotes'

urlpatterns = [
    path('Quotes/',views.index, name='Home'),
    path('author/<str:author_name>/', views.authores, name='author'),
    path('Author/create/', views.CreateAuthorView.as_view(), name='create_author'),
    path('Quote/create/', views.CreateQuoteView.as_view(), name='create_Quote'),

    
]

quote/quote/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('',include('Quotes.urls')),
    path('users/',include('users.urls')),
    path('admin/', admin.site.urls),
]

quote/users/urls.py
from django.urls import path
from .views import RegistView,ResetPasswordView
from .forms import LoginAuthenchens
from django.contrib.auth.views import LogoutView,LoginView,PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView


app_name='users'

urlpatterns = [
    path('Registration/', RegistView.as_view(), name='Log'),
    path('sign/', LoginView.as_view(template_name='users/sign.html', form_class=LoginAuthenchens, redirect_authenticated_user=True), name='Sign'),
    path('logout/', LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('reset-password/', ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

quote/Quotes/models.py
from django.db import models



class author(models.Model):
    fullname=models.CharField(max_length=100)
    born_date=models.CharField(max_length=90)
    born_location=models.CharField(max_length=200)
    description=models.TextField()

class Tag(models.Model):
    name=models.CharField(max_length=50,null=False,unique=True)

class Quote(models.Model):
    quote=models.TextField()
    author=models.ForeignKey(author, on_delete=models.CASCADE,default=None,null=True)
    tags=models.ManyToManyField(Tag)

quote/users/models.py
from django.db import models

quote/users/forms.py
from django.forms import ModelForm, ImageField,CharField,TextInput,FileInput,PasswordInput
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django import forms

class RegistForm(UserCreationForm):
    username =CharField(max_length=100, required=True, widget=TextInput(attrs={'class':'form-control'}))

    email =CharField(max_length=100, required=True, widget=TextInput(attrs={'class':'form-control'}))

    password1 =CharField(max_length=50, required=True, widget=PasswordInput(attrs={'class':'form-control'}))

    password2 =CharField(max_length=50, required=True, widget=PasswordInput(attrs={'class':'form-control'}))

    class Meta:
        model=User
        fields=('username','email','password1','password2')


class LoginAuthenchens(AuthenticationForm):
    
    username=CharField(max_length=100, required=True, widget=TextInput(attrs={'class':'form-control'}))
    password =CharField(max_length=50, required=True, widget=PasswordInput(attrs={'class':'form-control'}))

    class Meta:
        model=User
        fields=('username','password',)

quote/Quotes/views.py
from django.shortcuts import render, get_object_or_404
from .models import Quote,author,Tag
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.core.paginator import Paginator

def index(request):
    quote_list = Quote.objects.all()
    paginator = Paginator(quote_list, 10)  

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'Quotes/quotes.html', {'page_obj': page_obj})

def authores(request,author_name):
    author_instance = get_object_or_404(author, fullname=author_name)
    return render(request,'Quotes/Author.html',context={'author': author_instance})


class CreateAuthorView(LoginRequiredMixin, View):
    @method_decorator(login_required)
    def get(self, request):
        return render(request, 'Quotes/cret_athor.html')

    def post(self, request):
        fullname = request.POST.get('fullname')
        born_date = request.POST.get('born_date')
        born_location = request.POST.get('born_location')
        description = request.POST.get('description')

        authore = author.objects.create(
            fullname=fullname,
            born_date=born_date,
            born_location=born_location,
            description=description
        )

        return render(request, 'Quotes/cret_athor.html', context={'author': authore})
    


class CreateQuoteView(LoginRequiredMixin, View):
    @method_decorator(login_required)
    def get(self, request):
        authors = author.objects.all()

        tags = Tag.objects.all()
        return render(request, 'Quotes/cret_quote.html', context={'authors': authors, 'tags': tags})


    def post(self, request):
        quote = request.POST.get('quote')
        authosr = request.POST.get('author')
        tags = request.POST.getlist('tags')


        authore = author.objects.get(id=authosr)

        tags = Tag.objects.filter(id__in=tags)

        quote = Quote.objects.create(
            quote=quote,
            author=authore,
        )

        quote.tags.set(tags) 

        return render(request, 'Quotes/quotes.html', context={'quote': quote})

quote/users/views.py
from django.shortcuts import render,redirect
from django.views import View
from .forms import RegistForm
from django.contrib import messages
from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin

class RegistView(View):
    template_name='users/log.html'
    form_class=RegistForm

    def get(self,request):
        return render(request,self.template_name,{'form':self.form_class})

    def post(self,request):
        form=self.form_class(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data["username"]
            messages.success(request, f"Вітаємо {username}. Ваш акаунт успішно створено")
            return redirect('users:Sign')
        return render(request,self.template_name,{'form':form})
    



class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    html_email_template_name = 'users/password_reset_email.html'
    success_url = reverse_lazy('users:password_reset_done')
    success_message = "An email with instructions to reset your password has been sent to %(email)s."
    subject_template_name = 'users/password_reset_subject.txt'

quote/Quotes/templates/Quotes/Author.html
{% extends 'Quotes/base.html' %}

{% block title %} Author {% endblock %}
{% block content %}
<div class="container">
    


    <div class="author-details">
        <h3 class="author-title">{{author.fullname}}</h3>
        <p><strong>Born:</strong> <span class="author-born-date">{{author.born_date}}</span> <span class="author-born-location">{{author.born_location}}</span></p>
        <p><strong>Description:</strong></p>
        <div class="author-description">
            {{author.description}} 
           </div>
    </div>
    

</div>


{% endblock %}

quote/Quotes/templates/Quotes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    
    {% load static %}
    <link rel="stylesheet" href="{% static 'Quotes/style.css'%}">

    <title>Quotes</title>
</head>
<body>
    <div class="container">
        <div class="row header-box">
            <div class="col-md-8">
                <h1>
                    <a href=" {% url 'Quotes:Home' %}" style="text-decoration: none">Quotes to Scrape</a>
                </h1>
            </div>
            <div class="col-md-4">
                <p>
                    {% if user.is_authenticated %}
                        <a class="btn" href="{% url 'Quotes:create_author' %}"> Create Author</a>
                        <a class="btn" href="{% url 'Quotes:create_Quote' %}"> Create Quote</a>
                        <a class="btn" href="{% url 'users:logout' %}">Logout</a>
                    {% else %}
                        <a class="btn" href="{% url 'users:Sign' %}">Sign Up</a>
                        <a class="btn" href="{% url 'users:Log' %}">Login</a>
                    {% endif %}

                </p>
            </div>
        </div>
    


    </div>

    {% block content%}
    
    {% endblock %}

</body>
</html>

quote/Quotes/templates/Quotes/cret_athor.html
{% extends 'Quotes/base.html' %}

{% block title %} Create Author {% endblock %}

{% block content %}
<div class="container">
    <form method="post">
        {% csrf_token %}
{% if author %}
        <div class="mt-3">
            <h3>Author Created:</h3>
            <p>Name: {{ author.fullname }}</p>
            <p>Born Date: {{ author.born_date }}</p>
            <p>Born Location: {{ author.born_location }}</p>
            <p>Description: {{ author.description }}</p>
        </div>
{% else%}
        <h1>Create Author</h1>
        <div class="form-group">
            <label for="fullname">Full Name:</label>
            <input type="text" class="form-control" id="fullname" name="fullname" required>
        </div>
        <div class="form-group">
            <label for="born_date">Born Date:</label>
            <input type="text" class="form-control" id="born_date" name="born_date" required>
        </div>
        <div class="form-group">
            <label for="born_location">Born Location:</label>
            <input type="text" class="form-control" id="born_location" name="born_location" required>
        </div>
        <div class="form-group">
            <label for="description">Description:</label>
            <textarea class="form-control" id="description" name="description" rows="4" required></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Create</button>
    </form>

</div>
{% endif %}
{% endblock %}

quote/Quotes/templates/Quotes/cret_quote.html
{% extends 'Quotes/base.html' %}

{% block title %} Create Quote {% endblock %}
{% block content %}
<div class="container">
    <h1>Create Quote</h1>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="quote">Quote:</label>
            <textarea class="form-control" id="quote" name="quote" rows="4" required></textarea>
        </div>
        <div class="form-group">
            <label for="author">Author:</label>
            <select class="form-control" id="author" name="author" required>
                <option value="" disabled selected>Select an author</option>
                {% for author in authors %}
                    <option value="{{ author.id }}">{{ author.fullname }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <label>Tags:</label><br>
            {% for tag in tags %}
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="checkbox" id="tag{{ tag.id }}" name="tags" value="{{ tag.id }}">
                    <label class="form-check-label" for="tag{{ tag.id }}">{{ tag.name }}</label>
                </div>
            {% endfor %}
        </div>
        <button type="submit" class="btn btn-primary">Create</button>
    </form>
</div>
{% endblock %}

quote/Quotes/templates/Quotes/quotes.html
{% extends 'Quotes/base.html' %}

{% block title %} Quotes {% endblock %}
{% block content %}
<div class="container">
<div class="row">
    <div class="col-md-8"> 
        {% for quote in page_obj %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">
                “{{quote.quote}}”
            </span>
            <span>by <small class="author" itemprop="author">{{quote.author.fullname}}</small>
            <a href="{% url 'Quotes:author' quote.author.fullname %}">(about)</a>
            </span>
            <div class="tags">
                Tags:
                {% for tag in quote.tags.all  %}
                <a class="tag" href="/tag{{tag}}">{{tag.name}}</a>
                {% endfor %}

                
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="pagination">
        
        {% if page_obj.has_previous %}
            <a class="btn btn-primary" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}
    
        <span class="current-page">{{ page_obj.number }}</span>
    
        {% if page_obj.has_next %}
            <a class="btn btn-primary" href="?page={{ page_obj.next_page_number }}">Next</a>
        {% endif %}
    </div>
    
</div>
</div>
{% endblock %}

quote/Quotes/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <title>Quotes</title>
</head>
<body>
    <div class="container">
        <div class="row header-box">
            <div class="col-md-8">
                <h1>
                    <a href="/" style="text-decoration: none">Quotes to Scrape</a>
                </h1>
            </div>
            <div class="col-md-4">
                <p>
                    <a href="{% url 'users:Sign' %}">Sign Up</a>
                    <a href="{% url 'users:Log' %}">Login</a>
                    <a href="{% url 'users:logout' %}">Logout</a>
                </p>
            </div>
        </div>
    


    </div>

    {% block content%}
    
    {% endblock %}

</body>
</html>

quote/users/templates/users/log.html
{% extends 'Quotes/base.html' %}

{% block title %} Login {% endblock %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-6">
        <h1 class="mb-5">Registration User</h1>

        {% if form.errors and form.non_field_errors %}
        <span class="alert alert-danger" role="alert">{{ form.non_field_errors}}</span>
        {% endif %}

        <form method="post" class="login">
          {% csrf_token %}
          <div class="mb-3">  
            <lable class="form-label">Name
                {{form.username}}
            </lable>
            <span>{{form.errors.username}}</span>
          </div>

          <div class="mb-3">  
            <lable class="form-label">Email
                {{form.email}}
            </lable>
            <span>{{form.errors.email}}</span>
          </div>

          <div class="mb-3">  
            <lable class="form-label">Password
                {{form.password1}}
            </lable>
            <span>{{form.errors.password1}}</span>
          </div>
          
          <div class="mb-3">  
            <lable class="form-label">Confirm Password
                {{form.password2}}
            </lable>
            <span>{{form.errors.password2}}</span>
          </div>
          <button type="submit" class="btn btn-primary">Register</button>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

quote/users/templates/users/logout.html
{% extends 'Quotes/base.html' %}

{% block title %} Logout {% endblock %}

{% block content %}
<div class="container">
    <h1>Logout</h1>
    <p>Are you sure you want to log out?</p>
    <form method="post">
      {% csrf_token %}
      <button type="submit">Logout</button>
    </form>
  </div>
{% endblock %}

quote/users/templates/users/password_reset.html
{% extends "Quotes/base.html" %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-6">
        <h2 class="mb-5">Password reset</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Request password reset</button>
        </form>

{% endblock %}

quote/users/templates/users/password_reset_complete.html
{% extends "Quotes/base.html" %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-6">
        <h2 class="mb-5">Password reset complete!</h2>

{% endblock %}

quote/users/templates/users/password_reset_confirm.html
{% extends "Quotes/base.html" %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-6">
        <h2 class="mb-5">Enter new password</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Save new password</button>
        </form>

{% endblock %}

quote/users/templates/users/password_reset_done.html
{% extends "Quotes/base.html" %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-6">
        <h2 class="mb-6">Password reset request sent</h2>
        <p class="mb-3">We've emailed you with instructions on how to reset your password.</p>

{% endblock %}

quote/users/templates/users/password_reset_email.html
{% autoescape off %}
<body>
    <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-6">
            <p>Hi {{ user.username }},</p>
            <p>You requested a password reset for your account. Please follow this link to set a new password:</p>
            <p>
                <a href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">
                    {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
                </a>
            </p>
            <p>If you didn't request a password reset, please ignore this email.</p>
            <p>Thanks,</p>
            <p>The Our Team</p>
{% endautoescape %}

quote/users/templates/users/sign.html
{% extends "Quotes/base.html" %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-6">
        {% if messages %}
            <div>
                {% for message in messages %}
                    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
                {% endfor %}
            </div>
        {% endif %}

        <form  method="post" class="sign">
            {% csrf_token %}
            <div class="mb-3">
                <label class="form-label"> Username:
                    {{ form.username }}
                </label>
            </div>

            <div class="mb-3">
                <label class="form-label">Password:
                    {{ form.password }}
                </label>
            </div>

            <div class="grid">
                <button type="submit" class="btn btn-primary">Submit</button>
                <button type="reset" class="secondary">Reset</button>
            </div>
            <div class="small text-center">
                <a href="{% url 'users:password_reset' %}" class="text-center"><i>Forgot Password?</i></a>
            </div>
        </form>

{% endblock %}